# -*- coding: utf-8 -*-
import json, os

MESES = ["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"]

# Lista de tuplas: (mes, dia, anio, texto_dato, categoria)
# categoria in {"militar","ingenieria","exploracion","deportes","ciencia"}
data = []

def add(mes, dia, anio, dato, categoria):
    data.append((mes, dia, anio, dato, categoria))

# ======================= ENERO =======================
add(1,1,1925,"Edwin Hubble anunció que la Nebulosa de Andrómeda es una galaxia independiente, mucho más allá de la Vía Láctea.","ciencia")
add(1,2,1492,"Las tropas de los Reyes Católicos culminaron el asedio de Granada, poniendo fin al último reino musulmán en la península ibérica.","militar")
add(1,3,1777,"George Washington venció a las tropas británicas en la batalla de Princeton durante la guerra de independencia estadounidense.","militar")
add(1,4,1643,"Nació Isaac Newton, según el calendario gregoriano, una de las figuras centrales de la revolución científica.","ciencia")
add(1,5,1922,"Murió el explorador Ernest Shackleton a bordo del Quest, frente a Georgia del Sur, al comienzo de su última expedición antártica.","exploracion")
add(1,6,1912,"Alfred Wegener presentó por primera vez su teoría de la deriva continental.","ciencia")
add(1,7,1610,"Galileo Galilei observó por primera vez con su telescopio las lunas de Júpiter.","ciencia")
add(1,8,1889,"Herman Hollerith patentó una máquina tabuladora que sentó las bases de la computación de datos.","ingenieria")
add(1,9,1839,"Louis Daguerre presentó públicamente el daguerrotipo, uno de los primeros procesos fotográficos.","ingenieria")
add(1,10,1901,"Se descubrió petróleo en Spindletop, Texas, dando inicio al boom petrolero moderno de Estados Unidos.","ingenieria")
add(1,11,1922,"Se administró por primera vez insulina a un paciente humano con diabetes en Toronto.","ciencia")
add(1,12,1866,"Se fundó la Royal Aeronautical Society en Londres, la primera sociedad aeronáutica del mundo.","ingenieria")
add(1,13,1910,"El ingeniero Lee de Forest realizó una de las primeras transmisiones públicas de radio, emitiendo en vivo una función desde el Metropolitan Opera de Nueva York.","ingenieria")
add(1,14,1943,"Comenzó la Conferencia de Casablanca entre Roosevelt y Churchill para coordinar la estrategia militar aliada.","militar")
add(1,15,1967,"Se disputó el primer Super Bowl de la historia, entre Green Bay Packers y Kansas City Chiefs.","deportes")
add(1,16,1991,"Comenzó la campaña aérea de la Operación Tormenta del Desierto contra Irak.","militar")
add(1,17,1912,"Robert Falcon Scott alcanzó el Polo Sur, un mes después que la expedición noruega de Amundsen.","exploracion")
add(1,18,1778,"El capitán James Cook se convirtió en el primer europeo en avistar las islas de Hawái.","exploracion")
add(1,19,1839,"Charles Darwin fue elegido miembro de la Royal Society de Londres.","ciencia")
add(1,20,1892,"Se jugó en Springfield, Massachusetts, el primer partido oficial de baloncesto de la historia.","deportes")
add(1,21,1954,"Se botó el USS Nautilus, el primer submarino de propulsión nuclear del mundo.","ingenieria")
add(1,22,1879,"Comenzó la batalla de Rorke's Drift, una de las defensas militares británicas más célebres de la guerra anglo-zulú.","militar")
add(1,23,1849,"Elizabeth Blackwell se convirtió en la primera mujer en recibir un título de médica en Estados Unidos.","ciencia")
add(1,24,1986,"La sonda Voyager 2 de la NASA realizó su sobrevuelo más cercano a Urano.","exploracion")
add(1,25,1915,"Alexander Graham Bell realizó la primera llamada telefónica transcontinental de Estados Unidos, entre Nueva York y San Francisco.","ingenieria")
add(1,26,1788,"Llegó la Primera Flota británica a Sídney, fundando el primer asentamiento europeo en Australia.","exploracion")
add(1,27,1880,"Thomas Edison patentó la lámpara incandescente de larga duración.","ingenieria")
add(1,28,1986,"El transbordador espacial Challenger se desintegró 73 segundos después de su lanzamiento.","ingenieria")
add(1,29,1856,"La reina Victoria instituyó la Cruz Victoria, la más alta condecoración militar británica.","militar")
add(1,30,1968,"Comenzó la Ofensiva del Tet, una serie de ataques coordinados de las fuerzas norvietnamitas y del Vietcong durante la guerra de Vietnam.","militar")
add(1,31,1958,"Estados Unidos lanzó el Explorer 1, su primer satélite artificial.","exploracion")

# ======================= FEBRERO =======================
add(2,1,2003,"El transbordador espacial Columbia se desintegró al reingresar a la atmósfera, matando a sus siete tripulantes.","ingenieria")
add(2,2,1848,"Se firmó el Tratado de Guadalupe Hidalgo, que puso fin a la guerra entre México y Estados Unidos.","militar")
add(2,3,1966,"La sonda soviética Luna 9 realizó el primer alunizaje suave de la historia.","exploracion")
add(2,4,1938,"Se fundó Hewlett-Packard, cuyo primer producto fue un oscilador de precisión usado por Disney en la película Fantasía.","ingenieria")
add(2,5,1971,"El Apolo 14 alunizó en la región de Fra Mauro, con Alan Shepard y Edgar Mitchell a bordo.","exploracion")
add(2,6,1958,"El avión que trasladaba al equipo del Manchester United se estrelló en Múnich, en uno de los mayores desastres de la historia del fútbol.","deportes")
add(2,7,1985,"El astronauta Bruce McCandless realizó la primera caminata espacial sin cordón de seguridad, usando una unidad de maniobra.","exploracion")
add(2,8,1904,"Japón lanzó un ataque sorpresa contra la flota rusa en Port Arthur, dando inicio a la guerra ruso-japonesa.","militar")
add(2,9,1895,"William G. Morgan inventó el vóleibol en Massachusetts.","deportes")
add(2,10,1763,"Francia, España y Gran Bretaña firmaron el Tratado de París, que puso fin a la Guerra de los Siete Años.","militar")
add(2,11,2016,"Científicos del observatorio LIGO anunciaron la primera detección directa de ondas gravitacionales.","ciencia")
add(2,12,1809,"Nació en Inglaterra el naturalista Charles Darwin.","ciencia")
add(2,13,1945,"Comenzaron los bombardeos aliados sobre Dresde, uno de los ataques aéreos más destructivos de la Segunda Guerra Mundial.","militar")
add(2,14,1990,"La sonda Voyager 1 tomó la fotografía conocida como Pálido Punto Azul, mostrando a la Tierra desde los confines del sistema solar.","exploracion")
add(2,15,1898,"El acorazado USS Maine explotó en el puerto de La Habana, precipitando la guerra hispano-estadounidense.","militar")
add(2,16,1804,"El teniente Stephen Decatur lideró una incursión naval para incendiar la fragata capturada USS Philadelphia durante la guerra de Berbería.","militar")
add(2,17,1600,"El astrónomo Giordano Bruno fue ejecutado en Roma por la Inquisición, tras defender un universo infinito con múltiples soles.","ciencia")
add(2,18,1930,"El astrónomo Clyde Tombaugh descubrió el planeta enano Plutón.","ciencia")
add(2,19,1878,"Thomas Edison patentó el fonógrafo, el primer dispositivo capaz de grabar y reproducir sonido.","ingenieria")
add(2,20,1962,"John Glenn se convirtió en el primer estadounidense en orbitar la Tierra a bordo de la Friendship 7.","exploracion")
add(2,21,1885,"Se completó la construcción del Monumento a Washington, entonces la estructura más alta del mundo.","ingenieria")
add(2,22,1980,"El equipo estadounidense de hockey sobre hielo venció a la Unión Soviética en los Juegos Olímpicos de Lake Placid, en el partido conocido como Milagro sobre el Hielo.","deportes")
add(2,23,1945,"Marines estadounidenses izaron la bandera en el monte Suribachi durante la batalla de Iwo Jima.","militar")
add(2,24,1582,"El papa Gregorio XIII promulgó el calendario gregoriano, hoy usado en la mayor parte del mundo.","ciencia")
add(2,25,1836,"Samuel Colt patentó el revólver con cilindro giratorio.","ingenieria")
add(2,26,1616,"Galileo Galilei fue advertido formalmente por la Iglesia católica de abandonar la teoría heliocéntrica.","ciencia")
add(2,27,1991,"Terminaron los combates terrestres de la Guerra del Golfo tras la liberación de Kuwait.","militar")
add(2,28,1953,"James Watson y Francis Crick anunciaron el descubrimiento de la estructura de doble hélice del ADN.","ciencia")
add(2,29,1504,"Cristóbal Colón, varado en Jamaica, utilizó su conocimiento de un eclipse lunar inminente para persuadir a los habitantes locales de seguir abasteciendo a su tripulación.","exploracion")

# ======================= MARZO =======================
add(3,1,1954,"Estados Unidos detonó en el atolón Bikini la bomba de hidrógeno Castle Bravo, la mayor prueba nuclear de su historia.","militar")
add(3,2,1949,"El bombardero B-50 Lucky Lady II completó la primera vuelta al mundo sin escalas de la aviación.","militar")
add(3,3,1918,"Rusia firmó el Tratado de Brest-Litovsk, retirándose de la Primera Guerra Mundial.","militar")
add(3,4,1493,"Cristóbal Colón regresó a España tras completar su primer viaje a América.","exploracion")
add(3,5,1936,"Voló por primera vez el Spitfire, caza británico que sería clave en la Batalla de Inglaterra.","ingenieria")
add(3,6,1836,"Cayó el fuerte de El Álamo en Texas tras un sitio de trece días durante la guerra de independencia texana.","militar")
add(3,7,1876,"Alexander Graham Bell obtuvo la patente estadounidense del teléfono.","ingenieria")
add(3,8,1945,"Bombarderos B-29 estadounidenses realizaron un masivo ataque incendiario sobre Tokio.","militar")
add(3,9,1934,"Nació en la URSS Yuri Gagarin, quien se convertiría en el primer humano en viajar al espacio.","exploracion")
add(3,10,1876,"Alexander Graham Bell realizó la primera llamada telefónica exitosa de la historia.","ingenieria")
add(3,11,2011,"Un terremoto de magnitud 9,0 y el tsunami posterior provocaron el colapso de los sistemas de refrigeración de la central nuclear de Fukushima.","ingenieria")
add(3,12,1938,"Tropas alemanas entraron en Austria, formalizando el Anschluss.","militar")
add(3,13,1781,"William Herschel descubrió el planeta Urano.","ciencia")
add(3,14,1879,"Nació en Ulm, Alemania, el físico Albert Einstein.","ciencia")
add(3,15,44,"Julio César, general y dictador romano, fue asesinado en el Senado en los Idus de marzo.","militar")
add(3,16,1926,"Robert Goddard lanzó el primer cohete propulsado por combustible líquido de la historia.","ingenieria")
add(3,17,1958,"Estados Unidos lanzó el satélite Vanguard 1, el satélite artificial más antiguo que sigue en órbita.","exploracion")
add(3,18,1965,"El cosmonauta soviético Alekséi Leónov realizó la primera caminata espacial de la historia.","exploracion")
add(3,19,1687,"El explorador francés René-Robert Cavelier de La Salle fue asesinado por miembros de su propia expedición en Texas.","exploracion")
add(3,20,1815,"Napoleón Bonaparte entró en París al comienzo del periodo conocido como los Cien Días.","militar")
add(3,21,1918,"Alemania lanzó la Ofensiva de Primavera en el frente occidental, su último gran intento ofensivo de la Primera Guerra Mundial.","militar")
add(3,22,1945,"Fuerzas aliadas cruzaron el río Rin en la Operación Plunder, penetrando el territorio alemán en la recta final de la Segunda Guerra Mundial.","militar")
add(3,23,1854,"El inventor Elisha Otis demostró públicamente el primer ascensor de seguridad, con freno automático en caso de rotura del cable.","ingenieria")
add(3,24,1989,"El petrolero Exxon Valdez encalló en Alaska, provocando uno de los mayores derrames petroleros de la historia.","ingenieria")
add(3,25,1655,"Christiaan Huygens descubrió Titán, la mayor luna de Saturno.","ciencia")
add(3,26,1953,"Jonas Salk anunció el desarrollo exitoso de una vacuna contra la poliomielitis.","ciencia")
add(3,27,1964,"Un terremoto de magnitud 9,2 sacudió Alaska, uno de los más fuertes jamás registrados.","ciencia")
add(3,28,1979,"Ocurrió un accidente nuclear parcial en la central de Three Mile Island, Pensilvania.","ingenieria")
add(3,29,1974,"Agricultores chinos descubrieron el ejército de terracota en la tumba del primer emperador Qin Shi Huang.","exploracion")
add(3,30,1858,"Hyman Lipman patentó el primer lápiz con borrador incorporado.","ingenieria")
add(3,31,1889,"Se inauguró la Torre Eiffel en París con motivo de la Exposición Universal.","ingenieria")

# ======================= ABRIL =======================
add(4,1,1976,"Steve Jobs y Steve Wozniak fundaron Apple Computer en un garaje de California.","ingenieria")
add(4,2,1801,"El almirante Horatio Nelson venció a la flota danesa en la Batalla de Copenhague.","militar")
add(4,3,1973,"Martin Cooper realizó la primera llamada desde un teléfono celular portátil en Nueva York.","ingenieria")
add(4,4,1581,"La reina Isabel I de Inglaterra nombró caballero a Francis Drake tras su circunnavegación del globo.","exploracion")
add(4,5,1722,"El explorador neerlandés Jacob Roggeveen avistó la Isla de Pascua en domingo de Pascua, dándole su nombre.","exploracion")
add(4,6,1909,"Robert Peary afirmó haber alcanzado el Polo Norte junto a Matthew Henson.","exploracion")
add(4,7,1795,"Francia adoptó oficialmente el sistema métrico decimal.","ciencia")
add(4,8,1820,"Se descubrió la estatua de la Venus de Milo en la isla griega de Milos.","exploracion")
add(4,9,1865,"El general confederado Robert E. Lee se rindió ante Ulysses S. Grant en Appomattox, poniendo fin a la Guerra Civil estadounidense.","militar")
add(4,10,1930,"Se inauguró en Nueva York el edificio Chrysler, en su momento el rascacielos más alto del mundo.","ingenieria")
add(4,11,1970,"Estados Unidos lanzó la misión Apolo 13 rumbo a la Luna.","exploracion")
add(4,12,1961,"El cosmonauta soviético Yuri Gagarin se convirtió en el primer humano en viajar al espacio.","exploracion")
add(4,13,1970,"Un tanque de oxígeno explotó en el módulo de servicio del Apolo 13, forzando la cancelación del alunizaje.","exploracion")
add(4,14,1912,"El RMS Titanic chocó contra un iceberg en el Atlántico Norte poco antes de la medianoche.","ingenieria")
add(4,15,1912,"El RMS Titanic se hundió en el Atlántico tras chocar con un iceberg, causando la muerte de más de 1500 personas.","ingenieria")
add(4,16,1943,"El químico suizo Albert Hofmann sintetizó por primera vez la dietilamida de ácido lisérgico (LSD).","ciencia")
add(4,17,1970,"La tripulación del Apolo 13 amerizó a salvo en el océano Pacífico tras la explosión en vuelo.","exploracion")
add(4,18,1906,"Un terremoto de gran magnitud sacudió San Francisco, un episodio clave para el desarrollo de la sismología moderna.","ciencia")
add(4,19,1775,"Se libraron las batallas de Lexington y Concord, primeros enfrentamientos armados de la Revolución estadounidense.","militar")
add(4,20,1770,"El capitán James Cook avistó por primera vez la costa este de Australia.","exploracion")
add(4,21,1526,"Babur venció a las fuerzas del sultanato de Delhi en la primera batalla de Panipat, empleando artillería de campo por primera vez en la India.","militar")
add(4,22,1500,"El navegante portugués Pedro Álvares Cabral llegó a las costas de lo que hoy es Brasil.","exploracion")
add(4,23,1918,"La Marina Real británica lanzó el Raid de Zeebrugge para bloquear la base naval alemana de submarinos en Bélgica.","militar")
add(4,24,1990,"Se lanzó el telescopio espacial Hubble a bordo del transbordador Discovery.","ciencia")
add(4,25,1953,"James Watson y Francis Crick publicaron en la revista Nature su artículo sobre la estructura del ADN.","ciencia")
add(4,26,1937,"La Legión Cóndor alemana bombardeó la localidad vasca de Guernica durante la Guerra Civil española.","militar")
add(4,27,1521,"El explorador Fernando de Magallanes murió en la batalla de Mactán, en Filipinas.","exploracion")
add(4,28,1789,"La tripulación del HMS Bounty se amotinó contra el capitán William Bligh en el Pacífico Sur.","exploracion")
add(4,29,1913,"Gideon Sundback patentó una versión moderna y funcional del cierre de cremallera.","ingenieria")
add(4,30,1975,"Tropas norvietnamitas tomaron Saigón, poniendo fin a la guerra de Vietnam.","militar")

# ======================= MAYO =======================
add(5,1,1931,"Se inauguró el Empire State Building en la ciudad de Nueva York.","ingenieria")
add(5,2,1519,"Murió en Francia Leonardo da Vinci, cuyos cuadernos de estudios anatómicos y mecánicos anticiparon ideas científicas y de ingeniería de siglos posteriores.","ciencia")
add(5,3,1494,"Cristóbal Colón avistó por primera vez la isla de Jamaica durante su segundo viaje a América.","exploracion")
add(5,4,1904,"Estados Unidos inició la construcción del Canal de Panamá.","ingenieria")
add(5,5,1961,"Alan Shepard se convirtió en el primer estadounidense en viajar al espacio a bordo de la Freedom 7.","exploracion")
add(5,6,1937,"El dirigible Hindenburg se incendió al aterrizar en Nueva Jersey.","ingenieria")
add(5,7,1915,"Un submarino alemán hundió el transatlántico RMS Lusitania frente a las costas de Irlanda.","militar")
add(5,8,1945,"Alemania firmó su rendición incondicional, poniendo fin a la Segunda Guerra Mundial en Europa.","militar")
add(5,9,1926,"El explorador Richard Byrd afirmó haber sobrevolado por primera vez el Polo Norte en avión.","exploracion")
add(5,10,1869,"Se completó el primer ferrocarril transcontinental de Estados Unidos con la unión de las vías en Promontory, Utah.","ingenieria")
add(5,11,1997,"La computadora Deep Blue de IBM venció al campeón mundial de ajedrez Garri Kaspárov en un match completo.","ciencia")
add(5,12,1949,"Terminó el bloqueo soviético de Berlín tras casi once meses, superado por el puente aéreo aliado.","militar")
add(5,13,1940,"Alemania inició la invasión de Francia a través de las Ardenas, sorteando la Línea Maginot.","militar")
add(5,14,1973,"Estados Unidos lanzó al espacio la estación Skylab, su primera estación espacial.","exploracion")
add(5,15,1957,"El Reino Unido detonó su primera bomba de hidrógeno en el Pacífico, en la Operación Grapple.","militar")
add(5,16,1943,"Escuadrones de la RAF atacaron represas alemanas con bombas rebotantes especialmente diseñadas, en la célebre Operación Chastise.","militar")
add(5,17,1875,"Se disputó el primer Kentucky Derby en Louisville.","deportes")
add(5,18,1980,"El volcán Monte Santa Helena entró en erupción en el estado de Washington.","ciencia")
add(5,19,1935,"Murió en un accidente de motocicleta en Inglaterra el oficial T. E. Lawrence, conocido como Lawrence de Arabia.","militar")
add(5,20,1932,"Amelia Earhart despegó de Terranova para convertirse en la primera mujer en cruzar el Atlántico en solitario.","exploracion")
add(5,21,1927,"Charles Lindbergh aterrizó en París tras completar el primer vuelo transatlántico en solitario sin escalas.","exploracion")
add(5,22,1906,"Los hermanos Wright obtuvieron la patente de su máquina voladora.","ingenieria")
add(5,23,1430,"Juana de Arco fue capturada por tropas borgoñonas en Compiègne durante la guerra de los Cien Años.","militar")
add(5,24,1844,"Samuel Morse envió el primer mensaje telegráfico de larga distancia entre Washington y Baltimore.","ingenieria")
add(5,25,1961,"El presidente John F. Kennedy anunció ante el Congreso el objetivo de llevar un hombre a la Luna antes de 1970.","exploracion")
add(5,26,1940,"Comenzó la evacuación de tropas aliadas desde Dunkerque durante la Segunda Guerra Mundial.","militar")
add(5,27,1937,"Se abrió al tráfico el puente Golden Gate en San Francisco, entonces el puente colgante más largo del mundo.","ingenieria")
add(5,28,1959,"Los monos Able y Baker regresaron con vida a la Tierra tras un vuelo suborbital, validando el viaje espacial de primates.","exploracion")
add(5,29,1953,"Edmund Hillary y Tenzing Norgay alcanzaron por primera vez la cima del monte Everest.","exploracion")
add(5,30,1911,"Se disputó la primera edición de las 500 Millas de Indianápolis.","deportes")
add(5,31,1889,"La rotura de la presa South Fork provocó la catastrófica inundación de Johnstown, Pensilvania.","ingenieria")

# ======================= JUNIO =======================
add(6,1,1813,"La fragata estadounidense Chesapeake fue capturada por la Royal Navy británica frente a las costas de Boston.","militar")
add(6,2,1966,"La sonda Surveyor 1 de la NASA realizó el primer alunizaje suave estadounidense.","exploracion")
add(6,3,1965,"Edward White realizó la primera caminata espacial de un astronauta estadounidense durante la misión Gemini 4.","exploracion")
add(6,4,1942,"Comenzó la batalla de Midway, un punto de inflexión naval en el Pacífico durante la Segunda Guerra Mundial.","militar")
add(6,5,1967,"Israel lanzó un ataque aéreo preventivo contra Egipto, iniciando la Guerra de los Seis Días.","militar")
add(6,6,1944,"Fuerzas aliadas desembarcaron en Normandía en la mayor operación anfibia de la historia.","militar")
add(6,7,1099,"Comenzó el asedio cruzado a Jerusalén durante la Primera Cruzada.","militar")
add(6,8,1966,"Se anunció la fusión entre la NFL y la AFL, que dio origen al moderno fútbol americano profesional.","deportes")
add(6,9,1959,"Se botó el USS George Washington, primer submarino con misiles balísticos nucleares de la historia.","ingenieria")
add(6,10,1940,"Italia declaró la guerra a Francia y al Reino Unido, sumándose a la Segunda Guerra Mundial.","militar")
add(6,11,1997,"Michael Jordan anotó 38 puntos pese a una fuerte enfermedad, liderando a los Chicago Bulls a la victoria en el célebre Juego de la Gripe de las Finales de la NBA.","deportes")
add(6,12,1979,"El avión de propulsión humana Gossamer Albatross cruzó el canal de la Mancha por primera vez.","ingenieria")
add(6,13,1944,"Alemania lanzó el primer ataque con misiles V1 contra Londres.","militar")
add(6,14,1982,"Las fuerzas argentinas se rindieron ante el Reino Unido, poniendo fin a la guerra de las Malvinas.","militar")
add(6,15,1752,"Benjamin Franklin realizó su célebre experimento de la cometa para estudiar la naturaleza eléctrica de las tormentas.","ciencia")
add(6,16,1963,"La cosmonauta soviética Valentina Tereshkova se convirtió en la primera mujer en viajar al espacio.","exploracion")
add(6,17,1885,"Llegó a Nueva York la Estatua de la Libertad, desmontada en piezas enviadas desde Francia para su ensamblaje.","ingenieria")
add(6,18,1815,"El duque de Wellington derrotó a Napoleón Bonaparte en la batalla de Waterloo.","militar")
add(6,19,1846,"Se disputó en Hoboken, Nueva Jersey, el primer partido de béisbol bajo reglas modernas organizadas.","deportes")
add(6,20,1948,"Columbia Records presentó el disco de larga duración a 33⅓ revoluciones por minuto.","ingenieria")
add(6,21,1948,"Se presentó en Inglaterra el primer computador con programa almacenado en memoria, el Manchester Baby.","ingenieria")
add(6,22,1633,"Galileo Galilei fue obligado por la Inquisición a abjurar de la teoría heliocéntrica.","ciencia")
add(6,23,1868,"Christopher Latham Sholes patentó la primera máquina de escribir práctica.","ingenieria")
add(6,24,1859,"Se libró la batalla de Solferino, cuyo horror inspiraría la creación de la Cruz Roja.","militar")
add(6,25,1876,"Fuerzas lakota y cheyenes derrotaron al Séptimo de Caballería de Custer en la batalla de Little Bighorn.","militar")
add(6,26,1974,"Se escaneó el primer producto con código de barras en un supermercado de Ohio.","ingenieria")
add(6,27,1954,"La central nuclear de Óbninsk, en la URSS, se convirtió en la primera planta nuclear del mundo en generar electricidad para una red pública.","ingenieria")
add(6,28,1914,"El archiduque Francisco Fernando de Austria fue asesinado en Sarajevo, hecho que desencadenó la Primera Guerra Mundial.","militar")
add(6,29,2007,"Apple lanzó a la venta el primer iPhone, que transformó la industria de la telefonía móvil.","ingenieria")
add(6,30,1908,"Una gran explosión conocida como el evento de Tunguska arrasó una vasta zona de Siberia.","ciencia")

# ======================= JULIO =======================
add(7,1,1863,"Comenzó la batalla de Gettysburg, el enfrentamiento más sangriento de la Guerra Civil estadounidense.","militar")
add(7,2,1937,"La aviadora Amelia Earhart desapareció sobre el océano Pacífico durante su intento de vuelo alrededor del mundo.","exploracion")
add(7,3,1886,"Karl Benz presentó públicamente el Benz Patent-Motorwagen, considerado el primer automóvil.","ingenieria")
add(7,4,2012,"El CERN anunció el descubrimiento del bosón de Higgs.","ciencia")
add(7,5,1687,"Isaac Newton publicó los Principia Mathematica, obra fundacional de la física clásica.","ciencia")
add(7,6,1885,"Louis Pasteur aplicó con éxito la primera vacuna contra la rabia en un ser humano.","ciencia")
add(7,7,1930,"Comenzó la construcción de la presa Hoover en el río Colorado, Estados Unidos.","ingenieria")
add(7,8,1497,"Vasco da Gama zarpó de Lisboa en la expedición que abriría la ruta marítima europea hacia la India.","exploracion")
add(7,9,1893,"El cirujano Daniel Hale Williams realizó una de las primeras cirugías exitosas de corazón abierto.","ciencia")
add(7,10,1940,"Comenzó la batalla de Inglaterra, la campaña aérea entre la Luftwaffe alemana y la RAF británica.","militar")
add(7,11,1962,"Se realizó la primera transmisión de televisión vía satélite en vivo entre Estados Unidos y Europa mediante el satélite Telstar.","ingenieria")
add(7,12,1799,"Soldados franceses descubrieron la Piedra de Rosetta durante la campaña de Napoleón en Egipto.","exploracion")
add(7,13,1930,"Se disputó en Uruguay el primer partido de la historia de la Copa Mundial de Fútbol.","deportes")
add(7,14,1965,"La sonda Mariner 4 realizó el primer sobrevuelo exitoso de Marte, enviando las primeras imágenes cercanas de otro planeta.","exploracion")
add(7,15,1099,"Los cruzados cristianos conquistaron Jerusalén tras un prolongado asedio.","militar")
add(7,16,1945,"Estados Unidos detonó la primera bomba atómica de la historia en la prueba Trinity, en Nuevo México.","ciencia")
add(7,17,1975,"Naves Apolo y Soyuz se acoplaron en órbita, en la primera misión espacial conjunta entre Estados Unidos y la URSS.","exploracion")
add(7,18,1968,"Robert Noyce y Gordon Moore fundaron Intel, compañía clave en el desarrollo de los semiconductores modernos.","ingenieria")
add(7,19,1545,"Se hundió en el estrecho de Solent el buque de guerra inglés Mary Rose.","militar")
add(7,20,1969,"Neil Armstrong se convirtió en el primer humano en pisar la Luna.","exploracion")
add(7,21,1861,"Se libró la primera batalla de Bull Run, el primer gran enfrentamiento terrestre de la Guerra Civil estadounidense.","militar")
add(7,22,1298,"El rey Eduardo I de Inglaterra derrotó a los escoceses de William Wallace en la batalla de Falkirk.","militar")
add(7,23,1885,"Murió el general Ulysses S. Grant, comandante de las fuerzas de la Unión durante la Guerra Civil estadounidense.","militar")
add(7,24,1911,"El explorador Hiram Bingham redescubrió las ruinas incas de Machu Picchu en Perú.","exploracion")
add(7,25,1978,"Nació en Inglaterra Louise Brown, la primera persona concebida mediante fecundación in vitro.","ciencia")
add(7,26,1945,"Los Aliados emitieron la Declaración de Potsdam, exigiendo la rendición incondicional de Japón.","militar")
add(7,27,1953,"Se firmó el armisticio que puso fin a los combates de la Guerra de Corea.","militar")
add(7,28,1914,"Austria-Hungría declaró la guerra a Serbia, dando inicio formal a la Primera Guerra Mundial.","militar")
add(7,29,1958,"El Congreso de Estados Unidos creó la NASA, la agencia espacial civil del país.","exploracion")
add(7,30,1932,"Se inauguraron en Los Ángeles los Juegos Olímpicos de verano de 1932.","deportes")
add(7,31,1971,"Los astronautas del Apolo 15 condujeron por primera vez un vehículo lunar sobre la superficie de la Luna.","exploracion")

# ======================= AGOSTO =======================
add(8,1,1774,"El químico Joseph Priestley aisló por primera vez el oxígeno como gas.","ciencia")
add(8,2,1990,"Irak invadió Kuwait, desencadenando la crisis que llevaría a la Guerra del Golfo.","militar")
add(8,3,1492,"Cristóbal Colón zarpó del puerto de Palos rumbo a lo que sería el continente americano.","exploracion")
add(8,4,1914,"El Reino Unido declaró la guerra a Alemania tras la invasión de Bélgica, sumándose a la Primera Guerra Mundial.","militar")
add(8,5,1930,"Nació en Ohio el astronauta Neil Armstrong, quien años más tarde caminaría sobre la Luna.","exploracion")
add(8,6,1945,"Estados Unidos lanzó la primera bomba atómica usada en combate sobre la ciudad de Hiroshima.","militar")
add(8,7,1959,"La sonda Explorer 6 de la NASA envió la primera fotografía de la Tierra desde el espacio.","exploracion")
add(8,8,1918,"Comenzó la batalla de Amiens, ofensiva aliada que Erich Ludendorff calificó como el día negro del ejército alemán.","militar")
add(8,9,1945,"Estados Unidos lanzó una segunda bomba atómica sobre la ciudad japonesa de Nagasaki.","militar")
add(8,10,1519,"La expedición de Fernando de Magallanes zarpó de Sevilla rumbo a las Indias, en el viaje que terminaría siendo la primera circunnavegación del globo.","exploracion")
add(8,11,1929,"Babe Ruth se convirtió en el primer jugador de béisbol en conectar 500 cuadrangulares en su carrera.","deportes")
add(8,12,1908,"Henry Ford presentó el primer modelo del automóvil Ford T.","ingenieria")
add(8,13,1961,"Alemania Oriental comenzó a construir el Muro de Berlín para sellar la frontera con el sector occidental.","militar")
add(8,14,1945,"Japón anunció su rendición incondicional, poniendo fin a la Segunda Guerra Mundial.","militar")
add(8,15,1057,"El rey Macbeth de Escocia murió en batalla frente a las tropas de Malcolm III.","militar")
add(8,16,1780,"Tropas británicas derrotaron al ejército continental en la batalla de Camden durante la Revolución estadounidense.","militar")
add(8,17,1807,"El vapor Clermont de Robert Fulton realizó su primer viaje comercial exitoso por el río Hudson.","ingenieria")
add(8,18,1868,"El astrónomo francés Pierre Janssen detectó por primera vez el helio observando un eclipse solar en India.","ciencia")
add(8,19,1909,"Se disputó la primera carrera en el circuito de Indianapolis Motor Speedway.","deportes")
add(8,20,1977,"La NASA lanzó la sonda Voyager 2 rumbo a los planetas exteriores del sistema solar.","exploracion")
add(8,21,1888,"William Seward Burroughs patentó la primera calculadora sumadora de éxito comercial.","ingenieria")
add(8,22,1485,"Ricardo III de Inglaterra murió en la batalla de Bosworth, poniendo fin a la dinastía Plantagenet.","militar")
add(8,23,1305,"El líder escocés William Wallace fue ejecutado en Londres tras liderar la resistencia armada contra la ocupación inglesa.","militar")
add(8,24,79,"La erupción del volcán Vesubio sepultó las ciudades romanas de Pompeya y Herculano.","ciencia")
add(8,25,1919,"Se inauguró en Londres la primera línea aérea comercial internacional regular del mundo.","ingenieria")
add(8,26,1940,"La Real Fuerza Aérea británica bombardeó Berlín por primera vez durante la Segunda Guerra Mundial.","militar")
add(8,27,1883,"El volcán Krakatoa entró en una erupción catastrófica que se escuchó a miles de kilómetros de distancia.","ciencia")
add(8,28,1859,"Se registró el Evento Carrington, la tormenta geomagnética solar más intensa jamás documentada.","ciencia")
add(8,29,1949,"La Unión Soviética detonó su primera bomba atómica en Kazajistán.","militar")
add(8,30,1983,"Guion Bluford se convirtió en el primer afroestadounidense en viajar al espacio, a bordo del transbordador Challenger.","exploracion")
add(8,31,1897,"Thomas Edison patentó el Kinetógrafo, una de las primeras cámaras cinematográficas.","ingenieria")

# ======================= SEPTIEMBRE =======================
add(9,1,1939,"Alemania invadió Polonia, hecho que dio inicio a la Segunda Guerra Mundial.","militar")
add(9,2,1945,"Japón firmó su rendición formal a bordo del USS Missouri, poniendo fin a la Segunda Guerra Mundial.","militar")
add(9,3,1783,"Se firmó el Tratado de París que puso fin a la guerra de independencia de Estados Unidos.","militar")
add(9,4,1888,"George Eastman patentó la cámara Kodak con película en rollo, popularizando la fotografía.","ingenieria")
add(9,5,1977,"La NASA lanzó la sonda Voyager 1 rumbo al espacio exterior del sistema solar.","exploracion")
add(9,6,1522,"Regresó a España el Victoria, único barco superviviente de la expedición de Magallanes, completando la primera vuelta al mundo.","exploracion")
add(9,7,1812,"Se libró la batalla de Borodinó entre las tropas de Napoleón y el ejército ruso.","militar")
add(9,8,1943,"Italia anunció su armisticio con los Aliados, retirándose de la Segunda Guerra Mundial junto a Alemania.","militar")
add(9,9,9,"El general romano Varo perdió tres legiones ante las tribus germanas en la batalla del bosque de Teutoburgo.","militar")
add(9,10,1846,"Elias Howe patentó la máquina de coser con pespunte.","ingenieria")
add(9,11,2001,"Atentados terroristas derribaron las Torres Gemelas del World Trade Center en Nueva York.","militar")
add(9,12,1959,"La Unión Soviética lanzó la sonda Luna 2, el primer objeto humano en alcanzar la superficie lunar.","exploracion")
add(9,13,1759,"Fuerzas británicas vencieron a las francesas en la batalla de las Llanuras de Abraham, decidiendo el control de Quebec.","militar")
add(9,14,1752,"El Reino Unido adoptó el calendario gregoriano, saltando once días de golpe en su calendario oficial.","ciencia")
add(9,15,1916,"Se emplearon tanques por primera vez en combate, durante la batalla del Somme.","militar")
add(9,16,1620,"El Mayflower zarpó de Plymouth, Inglaterra, rumbo a América del Norte.","exploracion")
add(9,17,1862,"Se libró la batalla de Antietam, el día individual más sangriento de la Guerra Civil estadounidense.","militar")
add(9,18,1931,"Tropas japonesas provocaron el incidente de Mukden, pretexto para la invasión de Manchuria.","militar")
add(9,19,1356,"El Príncipe Negro venció a los franceses en la batalla de Poitiers durante la Guerra de los Cien Años.","militar")
add(9,20,1519,"La expedición de Fernando de Magallanes zarpó de Sanlúcar de Barrameda, en la etapa final antes de internarse en el Atlántico.","exploracion")
add(9,21,1780,"Se descubrió el plan de traición del general Benedict Arnold para entregar West Point a los británicos.","militar")
add(9,22,1980,"Comenzó la guerra entre Irak e Irán con una ofensiva iraquí a gran escala.","militar")
add(9,23,1846,"El astrónomo Johann Galle descubrió el planeta Neptuno.","ciencia")
add(9,24,1852,"Henri Giffard realizó el primer vuelo controlado de un dirigible propulsado por motor.","ingenieria")
add(9,25,1513,"El explorador Vasco Núñez de Balboa avistó por primera vez el océano Pacífico desde América.","exploracion")
add(9,26,1983,"El oficial soviético Stanislav Petrov evitó una posible guerra nuclear al identificar una falsa alarma de ataque.","militar")
add(9,27,1854,"El transatlántico SS Arctic naufragó en el Atlántico tras colisionar con otro barco, un episodio clave en la historia de la seguridad marítima.","ingenieria")
add(9,28,1928,"Alexander Fleming descubrió por accidente la penicilina en su laboratorio de Londres.","ciencia")
add(9,29,1988,"El transbordador espacial Discovery marcó el regreso de los vuelos tripulados de la NASA tras el desastre del Challenger.","exploracion")
add(9,30,1935,"Se completó la construcción de la presa Hoover en el río Colorado.","ingenieria")

# ======================= OCTUBRE =======================
add(10,1,1908,"Ford comenzó la producción en serie del automóvil Modelo T.","ingenieria")
add(10,2,1187,"El sultán Saladino conquistó Jerusalén tras derrotar a los cruzados.","militar")
add(10,3,1942,"Alemania lanzó con éxito el primer cohete V2, precursor de la exploración espacial moderna.","ingenieria")
add(10,4,1957,"La URSS lanzó el Sputnik 1, el primer satélite artificial de la historia.","exploracion")
add(10,5,1930,"El dirigible británico R101 se estrelló en Francia durante su vuelo inaugural a la India.","ingenieria")
add(10,6,1973,"Egipto y Siria lanzaron un ataque sorpresa contra Israel, iniciando la Guerra de Yom Kipur.","militar")
add(10,7,1913,"Henry Ford introdujo la primera línea de montaje móvil en la producción de automóviles.","ingenieria")
add(10,8,1918,"El sargento Alvin York protagonizó una de las acciones individuales más célebres de la Primera Guerra Mundial en el bosque de Argonne.","militar")
add(10,9,1936,"La presa Hoover comenzó a transmitir electricidad a Los Ángeles.","ingenieria")
add(10,10,1913,"Se voló la presa de Gamboa, uniendo por primera vez las aguas del Atlántico y el Pacífico a través del Canal de Panamá en construcción.","ingenieria")
add(10,11,1968,"La NASA lanzó el Apolo 7, la primera misión tripulada del programa Apolo.","exploracion")
add(10,12,1492,"Cristóbal Colón llegó a una isla del Caribe, iniciando el contacto europeo con América.","exploracion")
add(10,13,1943,"Italia declaró la guerra a Alemania, su antigua aliada del Eje.","militar")
add(10,14,1947,"Chuck Yeager se convirtió en el primer piloto en romper la barrera del sonido en vuelo controlado.","ingenieria")
add(10,15,1783,"Jean-François Pilâtre de Rozier realizó el primer ascenso humano en globo aerostático cautivo.","exploracion")
add(10,16,1968,"Bob Beamon estableció un récord mundial de salto largo que se mantendría vigente durante 23 años, en los Juegos Olímpicos de México.","deportes")
add(10,17,1888,"Thomas Edison presentó una patente preliminar para un dispositivo de cine, el cinetoscopio.","ingenieria")
add(10,18,1931,"Murió el inventor Thomas Edison, titular de más de mil patentes en Estados Unidos.","ingenieria")
add(10,19,1781,"El general británico Cornwallis se rindió en Yorktown, sellando la victoria de la independencia estadounidense.","militar")
add(10,20,1973,"Se inauguró oficialmente la Ópera de Sídney, un hito de la ingeniería y arquitectura moderna.","ingenieria")
add(10,21,1805,"La flota británica de Nelson venció a las armadas francesa y española en la batalla de Trafalgar.","militar")
add(10,22,1962,"El presidente Kennedy anunció el bloqueo naval a Cuba durante la crisis de los misiles.","militar")
add(10,23,42,"Marco Antonio y Octavio derrotaron a los asesinos de César en la batalla de Filipos.","militar")
add(10,24,1946,"Una cámara montada en un cohete V2 capturó la primera fotografía de la Tierra tomada desde el espacio.","exploracion")
add(10,25,1415,"El ejército inglés de Enrique V venció a los franceses en la batalla de Agincourt.","militar")
add(10,26,1863,"Se fundó en Londres la Football Association, que estableció las primeras reglas oficiales del fútbol.","deportes")
add(10,27,1904,"Se inauguró el primer tramo del metro subterráneo de la ciudad de Nueva York.","ingenieria")
add(10,28,1886,"Se inauguró oficialmente la Estatua de la Libertad en la bahía de Nueva York, con su armazón interno diseñado por Gustave Eiffel.","ingenieria")
add(10,29,1969,"Se envió el primer mensaje a través de ARPANET, la red precursora de internet.","ingenieria")
add(10,30,1961,"La Unión Soviética detonó la Bomba Zar, el artefacto nuclear más potente jamás probado.","militar")
add(10,31,1941,"Se completó la talla de los rostros presidenciales en el monumento del Monte Rushmore.","ingenieria")

# ======================= NOVIEMBRE =======================
add(11,1,1755,"Un devastador terremoto y posterior tsunami destruyeron gran parte de la ciudad de Lisboa, impulsando los primeros estudios científicos modernos sobre sismología.","ciencia")
add(11,2,1936,"La BBC inició el primer servicio regular de televisión de alta definición del mundo, en Londres.","ingenieria")
add(11,3,1957,"La Unión Soviética lanzó al espacio a la perra Laika a bordo del Sputnik 2.","exploracion")
add(11,4,1922,"El arqueólogo Howard Carter descubrió la entrada de la tumba de Tutankamón en Egipto.","exploracion")
add(11,5,1605,"Guy Fawkes fue descubierto intentando volar el Parlamento británico en la Conspiración de la Pólvora.","militar")
add(11,6,1935,"El ingeniero Edwin Armstrong hizo la primera demostración pública de la radiodifusión FM.","ingenieria")
add(11,7,1940,"El puente Tacoma Narrows, apodado Galloping Gertie, se derrumbó por resonancia inducida por el viento, cuatro meses después de su inauguración.","ingenieria")
add(11,8,1895,"Wilhelm Röntgen descubrió los rayos X.","ciencia")
add(11,9,1989,"Cayó el Muro de Berlín, símbolo del fin de la Guerra Fría en Europa.","militar")
add(11,10,1983,"Bill Gates presentó públicamente el primer sistema operativo Windows de Microsoft.","ingenieria")
add(11,11,1918,"Entró en vigor el armisticio que puso fin a los combates de la Primera Guerra Mundial.","militar")
add(11,12,1980,"La sonda Voyager 1 realizó su máximo acercamiento a Saturno.","exploracion")
add(11,13,1927,"Se inauguró el túnel Holland bajo el río Hudson, el primer túnel vehicular subacuático de largo alcance en Estados Unidos.","ingenieria")
add(11,14,1971,"La sonda Mariner 9 de la NASA se convirtió en la primera nave en orbitar otro planeta, Marte.","exploracion")
add(11,15,1988,"El transbordador soviético Burán realizó su único vuelo orbital, de forma totalmente automática y sin tripulación.","ingenieria")
add(11,16,1532,"El conquistador Francisco Pizarro capturó al inca Atahualpa en Cajamarca.","militar")
add(11,17,1869,"Se inauguró el Canal de Suez, que conecta el mar Mediterráneo con el mar Rojo.","ingenieria")
add(11,18,1963,"AT&T introdujo el primer teléfono con teclado de botones, reemplazando gradualmente el disco rotativo.","ingenieria")
add(11,19,1969,"Los astronautas del Apolo 12 alunizaron cerca de la sonda Surveyor 3, demostrando un alunizaje de precisión.","exploracion")
add(11,20,1945,"Comenzaron en Núremberg los juicios a los principales jerarcas nazis por crímenes de guerra.","militar")
add(11,21,1783,"Se realizó en París el primer vuelo tripulado en globo aerostático de la historia.","exploracion")
add(11,22,1943,"Roosevelt, Churchill y Chiang Kai-shek se reunieron en la Conferencia de El Cairo para coordinar la estrategia aliada contra Japón.","militar")
add(11,23,1876,"Se disputó en Buenos Aires el primer partido de fútbol documentado en Argentina.","deportes")
add(11,24,1859,"Charles Darwin publicó El origen de las especies.","ciencia")
add(11,25,1867,"Alfred Nobel patentó la dinamita.","ingenieria")
add(11,26,1965,"Francia lanzó el Astérix, su primer satélite artificial, convirtiéndose en la tercera potencia espacial del mundo.","exploracion")
add(11,27,1942,"La flota francesa se autohundió en Tolón para evitar que cayera en manos alemanas.","militar")
add(11,28,1520,"Fernando de Magallanes llegó al océano Pacífico tras cruzar el estrecho que hoy lleva su nombre.","exploracion")
add(11,29,1929,"El almirante Richard Byrd sobrevoló por primera vez el Polo Sur en avión.","exploracion")
add(11,30,1954,"Un meteorito impactó una casa en Sylacauga, Alabama, e hirió a una mujer, uno de los pocos casos documentados de una persona golpeada por un meteorito.","ciencia")

# ======================= DICIEMBRE =======================
add(12,1,1990,"Se completó bajo el Canal de la Mancha la conexión entre las perforadoras francesa y británica del Eurotúnel.","ingenieria")
add(12,2,1942,"Enrico Fermi logró la primera reacción nuclear en cadena autosostenida y controlada de la historia, en Chicago.","ciencia")
add(12,3,1967,"El cirujano Christiaan Barnard realizó el primer trasplante de corazón humano en Sudáfrica.","ciencia")
add(12,4,1965,"La NASA lanzó la misión Gemini 7, que estableció un récord de duración de vuelo espacial tripulado.","exploracion")
add(12,5,1492,"Cristóbal Colón desembarcó en la isla de La Española durante su primer viaje.","exploracion")
add(12,6,1917,"Una explosión de un barco municionero devastó el puerto de Halifax, Canadá, una de las mayores explosiones accidentales previas a la era nuclear.","ingenieria")
add(12,7,1941,"Japón atacó la base naval estadounidense de Pearl Harbor, Hawái.","militar")
add(12,8,1941,"Estados Unidos declaró la guerra a Japón tras el ataque a Pearl Harbor.","militar")
add(12,9,1968,"El ingeniero Douglas Engelbart presentó en público, por primera vez, el mouse de computadora, el hipertexto y la videoconferencia, en la célebre Madre de Todas las Demostraciones.","ingenieria")
add(12,10,1901,"Se entregaron por primera vez los premios Nobel en Estocolmo.","ciencia")
add(12,11,1972,"Los astronautas del Apolo 17 alunizaron en el valle de Taurus-Littrow, en la última misión tripulada a la Luna hasta la fecha.","exploracion")
add(12,12,1901,"Guglielmo Marconi recibió la primera señal de radio transatlántica de la historia.","ingenieria")
add(12,13,1577,"Francis Drake zarpó de Inglaterra en el viaje que lo convertiría en el primer inglés en circunnavegar el globo.","exploracion")
add(12,14,1911,"El explorador noruego Roald Amundsen se convirtió en el primer humano en alcanzar el Polo Sur.","exploracion")
add(12,15,1965,"Las naves Gemini 6 y Gemini 7 realizaron el primer encuentro orbital tripulado de la historia espacial.","exploracion")
add(12,16,1944,"Alemania lanzó su última gran ofensiva en el frente occidental, la batalla de las Ardenas.","militar")
add(12,17,1903,"Los hermanos Wright realizaron el primer vuelo controlado y sostenido de un avión con motor en Kitty Hawk.","ingenieria")
add(12,18,1912,"Se anunció el hallazgo del cráneo del Hombre de Piltdown en Inglaterra, más tarde revelado como uno de los fraudes científicos más célebres de la historia.","ciencia")
add(12,19,1777,"El ejército continental de George Washington se estableció en Valley Forge para pasar el crudo invierno.","militar")
add(12,20,1951,"El reactor experimental EBR-I, en Idaho, se convirtió en el primer reactor nuclear en generar electricidad utilizable.","ingenieria")
add(12,21,1620,"Los peregrinos del Mayflower desembarcaron en Plymouth, en la costa de Massachusetts.","exploracion")
add(12,22,1944,"Tropas estadounidenses rechazaron un ultimátum de rendición alemán durante el sitio de Bastogne.","militar")
add(12,23,1947,"Se demostró por primera vez el funcionamiento del transistor en los Laboratorios Bell.","ingenieria")
add(12,24,1968,"La tripulación del Apolo 8 se convirtió en la primera en orbitar la Luna.","exploracion")
add(12,25,1758,"El cometa Halley reapareció exactamente como había predicho el astrónomo Edmond Halley, confirmando post mortem su cálculo sobre la órbita del cometa.","ciencia")
add(12,26,1898,"Marie y Pierre Curie anunciaron el descubrimiento del elemento radio.","ciencia")
add(12,27,1831,"Charles Darwin zarpó de Inglaterra a bordo del HMS Beagle en su viaje de exploración científica.","exploracion")
add(12,28,1895,"Los hermanos Lumière realizaron la primera proyección pública de cine con su cámara-proyector, el cinematógrafo.","ingenieria")
add(12,29,1972,"El vuelo 401 de Eastern Air Lines se estrelló en los Everglades, un accidente que impulsó reformas clave en los procedimientos de seguridad de cabina de la aviación.","ingenieria")
add(12,30,1903,"Un incendio en el Iroquois Theatre de Chicago provocó reformas clave en los códigos de seguridad contra incendios de los edificios públicos.","ingenieria")
add(12,31,1968,"El Tupolev Tu-144 soviético se convirtió en el primer avión de pasajeros supersónico en volar, adelantándose semanas al Concorde.","ingenieria")

print(f"Total entradas generadas: {len(data)}")

result = []
for mes, dia, anio, dato, categoria in data:
    fecha_txt = f"{dia} de {MESES[mes-1]}, {anio} — {dato}"
    result.append({"month": mes, "day": dia, "year": anio, "text_es": fecha_txt, "category": categoria})

result.sort(key=lambda entry: (entry["month"], entry["day"]))

seen = set()
dupes = []
for e in result:
    key = (e["month"], e["day"])
    if key in seen:
        dupes.append(key)
    seen.add(key)

import calendar
expected = set()
for m in range(1,13):
    days_in_month = 29 if m == 2 else calendar.monthrange(2024, m)[1]
    for d in range(1, days_in_month+1):
        expected.add((m,d))

missing = expected - seen
extra = seen - expected

print(f"Duplicados: {dupes}")
print(f"Faltantes: {sorted(missing)}")
print(f"Sobrantes fuera de calendario: {sorted(extra)}")

out_dir = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(out_dir, "efemerides-366-es.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

print("JSON escrito en:", out_path)
